###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/5f33bd7fd58e7f5c48ce1bfb
###
GET http://localhost:3001/api/persons/NON-EXISTING
###
DELETE http://localhost:3001/api/persons/5f33bd7fd58e7f5c48ce1bfb
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Keke",
    "number": "329-048032"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Keke"
}